# Latent Semantic Indexing (LSI)

In [150]:
import sys 
import heapq 
import math
from collections import defaultdict # dictionary of lists
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

## 1. Function to extract terms and term frequency from document

In [151]:
def extract_from_file(filename):
    unformatted_words = []
    with open(filename,'r') as file:      
        for line in file:     
            for word in line.split():   
                unformatted_words.append(word)
    punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~1234567890'''
    dict_list=[]
    for word in unformatted_words:
        no_punct = ""
        for char in word:
            if char not in punctuations:
                no_punct = no_punct + char
        if no_punct != "":
            dict_list.append(no_punct.lower())
    key = []
    for word in dict_list:
        if word not in key:
            key.append(word)
    freq = []
    for i in range(len(key)):
        freq.append(dict_list.count(key[i]))
    dictionary=[]
    for i in range(len(key)):
        dictionary.append((key[i],freq[i]))
    dictionary.sort(key = lambda x: x[0])
    return dictionary

## 2. Function to return vector using terms in a document/query

In [152]:
def unpack_document(words):
    punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~1234567890'''
    dict_list=[]
    for word in words:
        no_punct = ""
        for char in word:
            if char not in punctuations:
                no_punct = no_punct + char
        if no_punct != "":
            dict_list.append(no_punct.lower())
    key = []
    for word in dict_list:
        if word not in key:
            key.append(word)
    freq = []
    for i in range(len(key)):
        freq.append(dict_list.count(key[i]))
    return key,freq
def get_vector(query_words,query_term_freq,final_words):
    query_vector=[]
    for word in final_words:
        if word not in query_words:
            query_vector.append(0)
        else:
            for i in range(len(query_words)):
                if word == query_words[i]:
                    query_vector.append(query_term_freq[i])
    query_vector=np.array(query_vector)
    return query_vector

## 3. Function to return Term Document Matrix for a given corpus 'doc_list'

In [153]:
def get_term_document_matrix(doc_list):
    n = len(doc_list)
    final_words=[]
    for i in range(n):
        for word,freq in doc_list[i]:
            if word not in final_words:
                final_words.append(word)
    final_words.sort()
    matrix=[]
    for word in final_words:
        temp=[]
        for i in range(n):
            present = False
            for doc_word,term_freq in doc_list[i]:
                if doc_word==word:
                    present = True
                    temp.append(term_freq)
            if present == False:
                temp.append(0)
        matrix.append(temp)
    return final_words,matrix

## 4. Execution

In [154]:
dict1 = extract_from_file("d1.txt")
dict2 = extract_from_file("d2.txt")
dict3 = extract_from_file("d3.txt")
doc_list=[dict1,dict2,dict3]
final_words,matrix = get_term_document_matrix(doc_list)
matrix = np.array(matrix)
print(final_words)
print(matrix)

['a', 'achieved', 'albert', 'all', 'also', 'although', 'an', 'and', 'another', 'anything', 'are', 'as', 'atom', 'be', 'because', 'been', 'being', 'between', 'bits', 'black', 'bodies', 'by', 'can', 'cannot', 'classical', 'communication', 'complete', 'concerning', 'confirmed', 'consistent', 'current', 'curvature', 'data', 'date', 'delay', 'depends', 'description', 'differ', 'differences', 'differential', 'dilation', 'dimensional', 'directly', 'einstein', 'electromagnetic', 'energy', 'entangled', 'entanglement', 'equations', 'especially', 'exact', 'exactly', 'examples', 'experimental', 'experiments', 'fall', 'faster', 'field', 'for', 'force', 'forces', 'four', 'free', 'from', 'fundamental', 'general', 'generalizes', 'geometric', 'geometry', 'gravitation', 'gravitational', 'gravity', 'has', 'have', 'help', 'holes', 'how', 'however', 'in', 'include', 'information', 'is', 'it', 'known', 'larger', 'law', 'laws', 'lensing', 'light', 'like', 'location', 'matter', 'modern', 'molecules', 'momentu

In [155]:
U, Sigma, V_t = np.linalg.svd(matrix, full_matrices=False)

In [156]:
print("U:",U)
print("\nSigma:",Sigma)
print("\nV:",V_t)
#print(U.shape,np.diag(Sigma).shape,V_t.shape)
#print(np.matmul(np.matmul(U,np.diag(Sigma)),V_t))

U: [[-0.09503946  0.02888772 -0.19519729]
 [-0.01121032 -0.07783613 -0.02452763]
 [-0.01859372  0.03235413 -0.07722173]
 [-0.02804799  0.00966147  0.06099551]
 [-0.01859372  0.03235413 -0.07722173]
 [-0.02804799  0.00966147  0.06099551]
 [-0.01121032 -0.07783613 -0.02452763]
 [-0.25562917  0.05440571 -0.13018632]
 [-0.01121032 -0.07783613 -0.02452763]
 [-0.01121032 -0.07783613 -0.02452763]
 [-0.01859372  0.03235413 -0.07722173]
 [-0.03718743  0.06470825 -0.15444346]
 [-0.01121032 -0.07783613 -0.02452763]
 [-0.07851662 -0.13634932  0.07293578]
 [-0.01121032 -0.07783613 -0.02452763]
 [-0.03925831 -0.06817466  0.03646789]
 [-0.02804799  0.00966147  0.06099551]
 [-0.03363097 -0.23350838 -0.07358288]
 [-0.01121032 -0.07783613 -0.02452763]
 [-0.02804799  0.00966147  0.06099551]
 [-0.02804799  0.00966147  0.06099551]
 [-0.03718743  0.06470825 -0.15444346]
 [-0.07851662 -0.13634932  0.07293578]
 [-0.01121032 -0.07783613 -0.02452763]
 [-0.08972694 -0.21418545  0.04840815]
 [-0.03363097 -0.23350

### Since we want to reduce query to two dimesnions, we only consider first 2 columns from U and V.
### and first two rows and first two columns from S

In [157]:
U_new = np.delete(U, -1, axis=1)
V_t_new = np.delete(V_t, -1,axis=0)
Sigma_new = np.delete(Sigma,-1)

In [158]:
print("U:",U_new)
print("\nSigma:",Sigma_new)
print("\nV:",V_t_new)

U: [[-0.09503946  0.02888772]
 [-0.01121032 -0.07783613]
 [-0.01859372  0.03235413]
 [-0.02804799  0.00966147]
 [-0.01859372  0.03235413]
 [-0.02804799  0.00966147]
 [-0.01121032 -0.07783613]
 [-0.25562917  0.05440571]
 [-0.01121032 -0.07783613]
 [-0.01121032 -0.07783613]
 [-0.01859372  0.03235413]
 [-0.03718743  0.06470825]
 [-0.01121032 -0.07783613]
 [-0.07851662 -0.13634932]
 [-0.01121032 -0.07783613]
 [-0.03925831 -0.06817466]
 [-0.02804799  0.00966147]
 [-0.03363097 -0.23350838]
 [-0.01121032 -0.07783613]
 [-0.02804799  0.00966147]
 [-0.02804799  0.00966147]
 [-0.03718743  0.06470825]
 [-0.07851662 -0.13634932]
 [-0.01121032 -0.07783613]
 [-0.08972694 -0.21418545]
 [-0.03363097 -0.23350838]
 [-0.02804799  0.00966147]
 [-0.02804799  0.00966147]
 [-0.02804799  0.00966147]
 [-0.05609598  0.01932293]
 [-0.01859372  0.03235413]
 [-0.01859372  0.03235413]
 [-0.02804799  0.00966147]
 [-0.02804799  0.00966147]
 [-0.02804799  0.00966147]
 [-0.01121032 -0.07783613]
 [-0.03718743  0.06470825

## 5. Query Input and modification

In [161]:
query = input("Enter query :").split(" ")

Enter query :quantum teleportation using general relativity.


In [162]:
#get the query terms and their frequencies
query_words,query_term_freq = unpack_document(query)
#convert query into vector
query_vector = get_vector(query_words,query_term_freq,final_words)
print(query_vector)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [163]:
#convert query into new reduced 2-dimensional query
new_query = np.matmul(query_vector.transpose(),U_new)
new_query = np.matmul(new_query,np.linalg.inv(np.diag(np.diag(V_t_new))))
print(new_query)

[0.86887203 0.10317704]


## 6. Rank documents in decreasing order of query-document cosine similarities. 

In [164]:
#unpack terms from documents of corpus
words = []
for dict_ in doc_list:
    words.append([a_tuple[0] for a_tuple in dict_])

#calculate terms and term_frequencies for documents in a corpus
doc_words,doc_tf=[],[]
for word_ in words:
    temp1,temp2=unpack_document(word_)
    doc_words.append(temp1)
    doc_tf.append(temp2)

#convert documents into vectors
doc_vectors=[]
for i in range(len(doc_words)):
    doc_vectors.append(get_vector(doc_words[i],doc_tf[i],final_words))

#reducing the document vector dimension
reduced_doc_vectors=[]
for doc_vector in doc_vectors:
    reduced_doc_vector = np.matmul(doc_vector.transpose(),U_new)
    reduced_doc_vector = np.matmul(reduced_doc_vector,np.linalg.inv(np.diag(np.diag(V_t_new))))
    reduced_doc_vectors.append(reduced_doc_vector)

In [165]:
print(reduced_doc_vectors)

[array([ 7.23903016, 19.23465717]), array([10.4552253 , -0.46291981]), array([  6.44428505, -56.87556669])]


In [166]:
#calculate cosine score
scores = []
for i in range(len(reduced_doc_vectors)):
    doc_score = cosine_similarity([new_query], [reduced_doc_vectors[i]])
    scores.append(doc_score[0][0])

In [167]:
ranked_documents=[]
for i in range(len(doc_list)):
    ranked_documents.append(("document-"+str(i+1),scores[i]))
ranked_documents.sort(key = lambda x: x[1],reverse=True)

In [168]:
print(ranked_documents)

[('document-2', 0.9868352391840663), ('document-1', 0.4601388043819571), ('document-3', -0.00537093761827058)]
